//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miku.Client.Assert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miku.Client.Assert.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下F10键 停止录制.
        /// </summary>
        public static string IntroductionContent {
            get {
                return ResourceManager.GetString("IntroductionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作说明.
        /// </summary>
        public static string IntroductionHeader {
            get {
                return ResourceManager.GetString("IntroductionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作说明.
        /// </summary>
        public static string IntroductionText {
            get {
                return ResourceManager.GetString("IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       只录制键盘.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入文件 .
        /// </summary>
        public static string LoadfileButtonContent {
            get {
                return ResourceManager.GetString("LoadfileButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将保存的动作文件载入为当前动作记录文件。.
        /// </summary>
        public static string LoadfileContentText {
            get {
                return ResourceManager.GetString("LoadfileContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       只录制鼠标.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       录制键盘和鼠标.
        /// </summary>
        public static string MouseAndKeyboard {
            get {
                return ResourceManager.GetString("MouseAndKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放动作.
        /// </summary>
        public static string PlaybackButtonContent {
            get {
                return ResourceManager.GetString("PlaybackButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键鼠动作当前录制文件下的动作回放。.
        /// </summary>
        public static string PlaybackContentText {
            get {
                return ResourceManager.GetString("PlaybackContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制动作.
        /// </summary>
        public static string RecordButtonContent {
            get {
                return ResourceManager.GetString("RecordButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键鼠动作的录制，录制开始后窗口将隐藏，F10键停止录制。.
        /// </summary>
        public static string RecordContentText {
            get {
                return ResourceManager.GetString("RecordContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录列表.
        /// </summary>
        public static string RecordedListHeader {
            get {
                return ResourceManager.GetString("RecordedListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回选项界面.
        /// </summary>
        public static string ReturnHomeTipText {
            get {
                return ResourceManager.GetString("ReturnHomeTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件 .
        /// </summary>
        public static string SavefileButtonContent {
            get {
                return ResourceManager.GetString("SavefileButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前动作录制的记录文件另存为。.
        /// </summary>
        public static string SavefileContentText {
            get {
                return ResourceManager.GetString("SavefileContentText", resourceCulture);
            }
        }
    }
}
