<?xml version="1.0" encoding="utf-8"?><Database Name="Miku" Class="MikuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Miku;Persist Security Info=True;User ID=sa" SettingsObjectName="Miku.DAL.Properties.Settings" SettingsPropertyName="MikuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SystemUser" Member="SystemUsers">
    <Type Name="SystemUser">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserState" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>